_extends: probot-settings

closeComment: >
  This issue has been closed automatically as it did not follow the issue template, please **open a new issue** that follows the bug report or feature request template.<br><br>

  Thank you! ✌️

matchComment: >
  Thanks so much for opening an issue!

allowNoTemplates: false
